Update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,13 +8,13 @@ fi
 
 # If cjson is not installed, install it
 sudo apt-get update
-sudo apt-get install -y libjson-c-dev
+sudo apt-get install -y libcjson-dev
 
 # Check if installation was successful
-if pkg-config --exists cjson; then
-    echo "cJSON has been installed successfully"
-    exit 0
-else
-    echo "Error: failed to install cJSON library."
-    exit 1
-fi
+# if pkg-config --exists cjson; then
+#     echo "cJSON has been installed successfully"
+#     exit 0
+# else
+#     echo "Error: failed to install cJSON library."
+#     exit 1
+# fi
